
using UdonSharp;
using UnityEngine;

namespace VRCVolumes
{
    /// <summary>
    /// Inherit from this class if you want to be able to get notified everytime the Volume generates a new Mesh.
    /// </summary>
    public class VolumeCallback : UdonSharpBehaviour
    {
        /// <summary>
        /// Gets called after a mesh was successfully generated by Volume.
        /// </summary>
        /// <param name="mesh">The generated mesh</param>
        /// <param name="collider">true if mesh was build for a collider</param>
        /// <param name="time">Time in milliseconds it took to generate the mesh</param>
        public virtual void OnAsyncMeshBuild(Mesh mesh, bool collider, long time) {}
    }
}